# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: CD - Deploy Site

trigger:
 branches:
  include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Deploy'
  inputs:
    command: 'run'
    projects: 'src/RodriBusCom/RodriBusCom.csproj'
    arguments: -- deploy
  env:
    ContentfulOptions__DeliveryApiKey: $(ContentfulOptions__DeliveryApiKey)
    ContentfulOptions__PreviewApiKey: $(ContentfulOptions__PreviewApiKey)
    ContentfulOptions__SpaceId: $(ContentfulOptions__SpaceId)
    GITHUB_TOKEN: $(GITHUB_TOKEN)
