# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: CD - Deploy Site

trigger:
 branches:
  include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  MinifyPages: $(MinifyPages)
  BeautifyPages: $(BeautifyPages)
  Host: $(Host)
  LinkRoot: $(LinkRoot)
  ContentfulOptions__SpaceId: $(ContentfulOptions__SpaceId)
  ContentfulOptions__DeliveryApiKey: $(ContentfulOptions__DeliveryApiKey)
  ContentfulOptions__PreviewApiKey: $(ContentfulOptions__PreviewApiKey)
  ContentfulOptions__Environment: $(ContentfulOptions__Environment)
  ContentfulOptions__ResolveEntriesSelectively: $(ContentfulOptions__ResolveEntriesSelectively)
  ContentfulOptions__UsePreviewApi: $(ContentfulOptions__UsePreviewApi)
  REPO_OWNER: $(REPO_OWNER)
  REPO_NAME: $(REPO_NAME)
  REPO_BRANCH: $(REPO_BRANCH)
  GITHUB_TOKEN: $(GITHUB_TOKEN)

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Deploy'
  inputs:
    command: 'run'
    projects: 'src/RodriBusCom/RodriBusCom.csproj'
    arguments: '--configuration $(buildConfiguration) -- deploy'
