//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Contentful.ModelGenerator.Cli tool.
//     Runtime Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Contentful.Core.Models;

namespace RodriBusCom.Models.Content
{
    public partial class Portfolio
    {
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public const string ContentTypeId = "portfolio";

        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public SystemProperties Sys { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public string Title { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public string Subtitle { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public Document Description { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public IEnumerable<string> Tags { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public Asset Banner { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public string Link { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public IEnumerable<IconLink> Links { get; set; }
        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public DateTime Year { get; set; }

        [GeneratedCode("Contentful.ModelGenerator.Cli", "1.0.0.0")]
        public async Task<string> RenderDescriptionAsync() => await new HtmlRenderer().ToHtml(Description);
    }
}